name: ec2 deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        required: true
        default: prod
        type: string

jobs:
  ecs_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Move to Laravel directory and install dependencies
        working-directory: ./src/laravel
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Deploy Laravel application to S3 and capture eTag
        id: s3-deploy
        working-directory: ./src/laravel
        run: |
          OUTPUT=$(aws deploy push \
            --application-name ${{ secrets.AWS_DEPLOY_APP_NAME }} \
            --s3-location s3://${{ secrets.AWS_DEPLOY_SOURCE_BUCKET_NAME }}/${{ github.run_id }}.zip --no-ignore-hidden-files)
          echo "$OUTPUT"
          ETAG=$(echo "$OUTPUT" | grep -oP 'eTag=\K[^ ]+')
          echo "etag=$ETAG" >> $GITHUB_OUTPUT

      - name: Create deployment with AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_DEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.AWS_DEPLOY_GROUP_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=${{ secrets.AWS_DEPLOY_SOURCE_BUCKET_NAME }},bundleType=zip,key=${{ github.run_id }}.zip,eTag=${{ steps.s3-deploy.outputs.etag }}

      - name: Slack Notify
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,took,ref,author,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
