name: ecs deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        required: true
        default: prod
        type: string
      secrets:
        AWS_ROLE_TO_ASSUME:
          required: true
        SLACK_WEBHOOK_URL:
          required: true

jobs:
  ecs_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentias@v1-node16
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: Slack Notify
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,took,ref,author,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}